# Generated by Django 5.0 on 2023-12-12 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название')),
                ('gramm', models.CharField(max_length=10, verbose_name='Литры')),
                ('sostav', models.TextField(verbose_name='Описание')),
                ('price', models.CharField(max_length=10, verbose_name='Цена')),
            ],
        ),
    ]
