# Generated by Django 5.0 on 2023-12-12 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='type',
            field=models.CharField(default=0, max_length=30, verbose_name='Тип'),
            preserve_default=False,
        ),
    ]
