# Generated by Django 5.0 on 2023-12-15 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_position_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='position',
            options={'verbose_name': 'Позиция', 'verbose_name_plural': 'Позиции меню'},
        ),
        migrations.AlterField(
            model_name='position',
            name='price',
            field=models.IntegerField(verbose_name='Цена'),
        ),
    ]
